---
title: thebasics
url: http://thebasics.siteleaf.net
timezone: Pacific/Auckland
collections:
  a-collection:
    title: A-Collection
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
