---
title: thebasics
url: http://thebasics.siteleaf.net
timezone: Pacific/Auckland
collections:
  a-collection-of-basketballs:
    title: A collection of basketballs
    output: true
  a-collection:
    title: A-Collection
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
