---
title: thebasics
url: http://thebasics.siteleaf.net
timezone: Pacific/Auckland
collections:
  balls:
    title: Balls
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
